(lang dune 3.21)

(name pgn2tex)

(generate_opam_files true)

(source
 (github therealowenrees/pgn2tex))

(authors "Owen Rees <owenrees.dev@gmail.com>")

(maintainers "Owen Rees <owenrees.dev@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name pgn2tex)
 (synopsis "A chess PGN to TeX conversion tool")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
